version: "3.1"
services:
  postgres:
    container_name: blog_app
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog_app
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
